version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
  groups:
    "all-docker-updates":
      patterns:
        - "*"
- package-ecosystem: pip
  directories:
    - "/bots/*"
  schedule:
    interval: weekly
  groups:
    "all-pip-updates":
      patterns:
        - "*"
