repos:
  - repo: local
    hooks:
      - id: generate-config-example-from-env-examples
        name: Generate config example from env examples
        entry: bash -c 'python3 scripts/gen_config.py > config.json.example'
        language: python
        pass_filenames: false
        additional_dependencies: ["python-dotenv"]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.15
    hooks:
      # Sort imports.
      - id: ruff
        args: ["check", "--select", "I", "--fix"]
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [ --fix ]
